[main]
#font=JetBrainsMono Nerd Font Mono:size=12
font=JetBrainsMono Nerd Font Mono:style=Regular
font-bold=JetBrainsMono Nerd Font Mono:style=Bold
font-italic=JetBrainsMono Nerd Font Mono:style=Italic
font-bold-italic=JetBrainsMono Nerd Font Mono:style=Bold Italic
#pad=8x8
dpi-aware=yes

[colors]
alpha=0.80
