[main]

# JetBrains Nerd
#font=JetBrainsMono Nerd Font Mono:size=12
#font=JetBrainsMono Nerd Font Mono:style=Regular
#font-bold=JetBrainsMono Nerd Font Mono:style=Bold
#font-italic=JetBrainsMono Nerd Font Mono:style=Italic
#font-bold-italic=JetBrainsMono Nerd Font Mono:style=Bold Italic
#
#Noto Nerd
#
font=Noto Sans Mono:style=Regular:size=12, NotoSans Nerd Font:style=Regular
font-bold=Noto Sans Mono:style=Bold:size=12, NotoSans Nerd Font:style=Bold
font-italic=Noto Sans Mono:style=Italic:size=12, NotoSans Nerd Font:style=Italic
font-bold-italic=Noto Sans Mono:style=Bold Italic:size=12, NotoSans Nerd Font:style=Bold Italic
#dpi-aware=yes
#pad=8x8

[colors]
alpha=0.80
