# Old config
#preload = ~/Documents/Backgrounds/Kath.png
#wallpaper = eDP-1,~/Documents/Backgrounds/Kath.png


# New config
wallpaper {
    monitor = eDP-1
    path = ~/Documents/Backgrounds/1-nord.png
    fit_mode = cover
}


# ...
